name: Upload the Python package to PyPI.
on: 
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install poetry-dynamic-versioning
          run: pip install poetry-dynamic-versioning

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      
      - name: Build Package
        run: poetry build
      
      - name: Upload to PyPI
        env:
          PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish -u shmokmt -p "$PASSWORD"
