name: reviewdog
on: 
  pull_request:
    branches:
      - master
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: python
#        uses: wemake-services/wemake-python-styleguide
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          github_token: $ {{ secrets.REVIEWDOG }}
          level: warning
          locale: "US"
